Models/ErrorViewModel.cs
namespace GerenciamentoLojaMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FuncionariosModel.cs
using System.ComponentModel.DataAnnotations;

namespace GerenciamentoLojaMVC.Models
{
    public class FuncionariosModel
    {
            [Key]
            public int FuncionarioId { get; set; }

            [Required(ErrorMessage = "Digite o nome do funcionário")]
            public string NomeFuncionario { get; set; } = string.Empty;

            [Required(ErrorMessage = "Digite o cargo do funcionário")]
            public string CargoFuncionario { get; set; } = string.Empty;

            [Required(ErrorMessage = "Digite o salário do funcionário")]
            public decimal SalarioFuncionario { get; set; }

            [Required(ErrorMessage = "Digite o e-mail do funcionário")]
            public string Email { get; set; } = string.Empty;

            [Required(ErrorMessage = "Digite o telefone do funcionário")]
            public string Telefone { get; set; } = string.Empty;

    }
}

Models/ProdutosModel.cs
using System.ComponentModel.DataAnnotations;

namespace GerenciamentoLojaMVC.Models
{
    public class ProdutosModel
    {
        [Key]
        public int ProdutoId { get; set; }

        [Required(ErrorMessage = "Digite o nome do produto")]
        public string Nome { get; set; } = string.Empty;

        [Required(ErrorMessage = "Digite a descrição do produto")]
        public string Descricao { get; set; } = string.Empty;

        [Required(ErrorMessage = "Digite a quantidade do produto")]
        public int Quantidade { get; set; }

        [Required(ErrorMessage = "Digite a categoria do produto")]
        public string Categoria { get; set; } = string.Empty;
        public DateTime DataCadastro { get; set; } = DateTime.Now;
    }
}

Controllers/FuncionariosController.cs
using GerenciamentoLojaMVC.Data;
using GerenciamentoLojaMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace GerenciamentoLojaMVC.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly ApplicationDbContext _db;
        public FuncionariosController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<FuncionariosModel> funcionarios = _db.Funcionarios;
            return View(funcionarios);
        }
            
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

       
        [HttpPost]
        public IActionResult Cadastrar(FuncionariosModel funcionarios)
        {
            if (ModelState.IsValid)
            {
                _db.Funcionarios.Add(funcionarios);
                _db.SaveChanges();

               TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            FuncionariosModel funcionarios = _db.Funcionarios.FirstOrDefault(x => x.FuncionarioId == id);

            if (funcionarios == null)
            {
                return NotFound();
            }

            return View(funcionarios);
        }

        [HttpPost]
        public IActionResult Editar(FuncionariosModel funcionarios)
        {
            if (ModelState.IsValid)
            {
                _db.Funcionarios.Update(funcionarios);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Edição realizada com sucesso!";

                return RedirectToAction("Index");
            }

            return View(funcionarios);
        }

        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            FuncionariosModel funcionarios = _db.Funcionarios.FirstOrDefault(x => x.FuncionarioId==id);

            if (funcionarios == null)
            {
                return NotFound();
            }

            return View(funcionarios);
        }

        [HttpPost]
        public IActionResult Excluir(FuncionariosModel funcionarios)
        {
            if (ModelState.IsValid)
            {
                _db.Funcionarios.Remove(funcionarios);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Exclusão realizada com sucesso!";

                return RedirectToAction("Index");
            }

            return View(funcionarios);
        }

    }
}

Controllers/HomeController.cs
using GerenciamentoLojaMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GerenciamentoLojaMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProdutosController.cs
using GerenciamentoLojaMVC.Data;
using GerenciamentoLojaMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace GerenciamentoLojaMVC.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly  ApplicationDbContext _db;
        public ProdutosController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<ProdutosModel> produtos = _db.Produtos;
            return View(produtos);
        }

        [HttpGet]
         public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(ProdutosModel produtos)
        {
            if (ModelState.IsValid) 
            {
                _db.Produtos.Add(produtos);
                _db.SaveChanges();
                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
      
            ProdutosModel produtos = _db.Produtos.FirstOrDefault(x => x.ProdutoId == id);
          
            if (produtos == null)
            {
                return NotFound();
            }
            
            return View(produtos);
        }

        [HttpPost]
        public IActionResult Editar(ProdutosModel produtos)
        {
            if (ModelState.IsValid)
            {
                _db.Produtos.Update(produtos);
                _db.SaveChanges();
                TempData["MensagemSucesso"] = "Edição realizada com sucesso!";
                return RedirectToAction("Index");
            }

            return View(produtos);
        }

        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }

            ProdutosModel produtos = _db.Produtos.FirstOrDefault(x => x.ProdutoId == id);

            if (produtos == null)
            {
                return NotFound();
            }

            return View(produtos);
        }

        [HttpPost]
        public IActionResult Excluir(ProdutosModel produtos)
        {
            if (ModelState.IsValid)
            {
                _db.Produtos.Remove(produtos);
                _db.SaveChanges();
                TempData["MensagemSucesso"] = "Remoção realizada com sucesso!";
                return RedirectToAction("Index");
            }

            return View(produtos);
        }
    }
}

Views/Funcionarios/Cadastrar.cshtml
@model FuncionariosModel
@{
    ViewData["title"] = "Cadastrar funcionario";
}

<div class="container bg-dark p-5 rounded-5">
      <div class="mb-5 text-center">
        <h1 class=text-light>Cadastro de funcionarios</h1>
    </div>

    <form method="post" asp-controller="Funcionarios" asp-action="Cadastrar">
    <div class="form-group">
    <label for="Nome">Nome:</label>
    <input type="text" class="form-control" asp-for="NomeFuncionario" id="Nome" placeholder="Digite nome do funcionário">
     <span asp-validation-for="NomeFuncionario" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Cargo">Cargo:</label>
    <input type="text" class="form-control" asp-for="CargoFuncionario" id="Cargo" placeholder="Digite o cargo do funcionário">
    <span asp-validation-for="CargoFuncionario" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Salario">Salário: </label>
    <input type="number" class="form-control" asp-for="SalarioFuncionario" id="Salario" placeholder="Digite o valor do salário">
     <span asp-validation-for="SalarioFuncionario" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Email">E-mail: </label>
    <input type="email" class="form-control" asp-for="Email" id="Email" placeholder="Digite o E-mail do funcionário">
     <span asp-validation-for="Email" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Telefone">Telefone: </label>
    <input type="tel" class="form-control mb-5" asp-for="Telefone" id="Telefone" placeholder="Digite o telefone do funcionário">
     <span asp-validation-for="Telefone" class=text-warning></span>
  </div>
 
  <div class="d-flex gap-5 mt-6">
    <button type="submit" class="btn btn-success w-50">Adicionar</button>
    <a class="btn btn-primary w-50" asp-controller="Funcionarios" asp-action="Index">Voltar</a>
  </div>
</form>
</div>

Views/Funcionarios/Editar.cshtml
@model FuncionariosModel
@{
    ViewData["title"] = "Edição de funcionario";
}

<div class="container bg-dark p-5 rounded-5">
      <div class="mb-5 text-center">
        <h1 class=text-light>Edição de funcionarios</h1>
    </div>

    <form method="post" asp-controller="Funcionarios" asp-action="Editar">
        <input type="hidden" asp-for="FuncionarioId"/>
    <div class="form-group">
    <label for="Nome">Nome:</label>
    <input type="text" class="form-control" asp-for="NomeFuncionario" id="Nome" placeholder="Digite nome do funcionário">
     <span asp-validation-for="NomeFuncionario" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Cargo">Cargo:</label>
    <input type="text" class="form-control" asp-for="CargoFuncionario" id="Cargo" placeholder="Digite o cargo do funcionário">
    <span asp-validation-for="CargoFuncionario" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Salario">Salário: </label>
    <input type="number" class="form-control" asp-for="SalarioFuncionario" id="Salario" placeholder="Digite o valor do salário">
     <span asp-validation-for="SalarioFuncionario" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Email">E-mail: </label>
    <input type="email" class="form-control" asp-for="Email" id="Email" placeholder="Digite o E-mail do funcionário">
     <span asp-validation-for="Email" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Telefone">Telefone: </label>
    <input type="tel" class="form-control mb-5" asp-for="Telefone" id="Telefone" placeholder="Digite o telefone do funcionário">
     <span asp-validation-for="Telefone" class=text-warning></span>
  </div>

  <div class="d-flex gap-5 mt-6">
    <button type="submit" class="btn btn-success w-50">Adicionar</button>
    <a class="btn btn-primary w-50" asp-controller="Funcionarios" asp-action="Index">Voltar</a>
  </div>
</form>
</div>

Views/Funcionarios/Excluir.cshtml
@model FuncionariosModel
@{
    ViewData["title"] = "Exclusão de funcionario";
}

<div class="container bg-dark p-5 rounded-5">
      <div class="mb-5 text-center">
        <h1 class=text-light>Exclusão de funcionarios</h1>
    </div>

    <form method="post" asp-controller="Funcionarios" asp-action="Excluir">
        <input type="hidden" asp-for="FuncionarioId"/>
    <div class="form-group">
    <label for="Nome">Nome:</label>
    <input type="text" class="form-control" asp-for="NomeFuncionario" id="Nome" placeholder="Digite nome do funcionário">
     <span asp-validation-for="NomeFuncionario" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Cargo">Cargo:</label>
    <input type="text" class="form-control" asp-for="CargoFuncionario" id="Cargo" placeholder="Digite o cargo do funcionário">
    <span asp-validation-for="CargoFuncionario" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Salario">Salário: </label>
    <input type="number" class="form-control" asp-for="SalarioFuncionario" id="Salario" placeholder="Digite o valor do salário">
     <span asp-validation-for="SalarioFuncionario" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Email">E-mail: </label>
    <input type="email" class="form-control" asp-for="Email" id="Email" placeholder="Digite o E-mail do funcionário">
     <span asp-validation-for="Email" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Telefone">Telefone: </label>
    <input type="tel" class="form-control mb-5" asp-for="Telefone" id="Telefone" placeholder="Digite o telefone do funcionário">
     <span asp-validation-for="Telefone" class=text-warning></span>
  </div>

  <div class="d-flex gap-5 mt-6">
    <button type="submit" class="btn btn-danger w-50">Excluir funcionário</button>
    <a class="btn btn-primary w-50" asp-controller="Funcionarios" asp-action="Index">Voltar</a>
  </div>
</form>
</div>

Views/Funcionarios/Index.cshtml
@model IEnumerable<FuncionariosModel>

@{
	ViewData["title"] = "Página principal";
}

<div class="container">
     <div class="d-flex justify-content-between align-items-center mb-5">
     <h1>Funcionarios</h1>
     <a class="btn btn-success mx-2" asp-controller="Funcionarios" asp-action="Cadastrar">Cadastrar novo funcionario</a>
     </div>  
    @if (TempData["MensagemSucesso"] != null)
    {
                <div class="alert alert-success bg-success text-light" role="alert">
            @TempData["MensagemSucesso"]
                </div>
    }
<table id="Funcionarios" class="table table-hover table-dark">
     <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Cargo</th>
      <th scope="col">Salário</th>
      <th scope="col">Email</th>
      <th scope="col">Telefone</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
            @if (Model != null)
            {
                @foreach (var funcionario in Model)
                {
                        <tr>
                        <td scope="row">@funcionario.NomeFuncionario</td>
                        <td>@funcionario.CargoFuncionario</td>
                               <td>@funcionario.SalarioFuncionario.ToString("0.000")</td>

                        <td>@funcionario.Email</td> 
                        <td>@funcionario.Telefone</td>
                        <td>
                           <a class="btn btn-primary mx-2" asp-controller="Funcionarios" asp-action="Editar" asp-route-id="@funcionario.FuncionarioId">Editar</a>
                           <a class="btn btn-danger mx-2" asp-controller="Funcionarios" asp-action="Excluir" asp-route-id="@funcionario.FuncionarioId">Excluir</a>
                       </td>
                        </tr>
                }
            }
  </tbody>
</table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
}

<div class="text-center">
    <h1 class="display-4">Gerenciamento de Loja</h1>
    <div>
        <img src="img/digital.png"/>
    </div>
</div>

Views/Produtos/Cadastrar.cshtml
@model ProdutosModel
@{
	ViewData["title"] = "Cadastrar produto";
}

<div class="container bg-dark p-5 rounded-5">
	  <div class="mb-5 text-center">
		<h1 class=text-light>Cadastro de produtos</h1>
	</div>
    
    <form method="post" asp-controller="Produtos" asp-action="Cadastrar">
  <div class="form-group">
    <label for="Nome">Nome:</label>
    <input type="text" class="form-control" asp-for="Nome" id="Nome" placeholder="Digite nome do produto">
     <span asp-validation-for="Nome" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Descricao">Descrição:</label>
    <input type="text" class="form-control" asp-for="Descricao" id="Descricao" placeholder="Digite uma breve descrição do produto">
    <span asp-validation-for="Descricao" class=text-warning></span>
  </div>
   <div class="form-group">
    <label for="Quantidade">Quantidade: </label>
    <input type="text" class="form-control" asp-for="Quantidade" id="Quantidade" placeholder="Digite a quantidade">
     <span asp-validation-for="Quantidade" class=text-warning></span>
  </div>
  <div class="form-group">
    <label for="Categoria">Categoria:</label>
    <select class="form-control mb-5" asp-for="Categoria" id="Categoria" placeholder="Selecione a categoria">
        <option> Selecione a categoria</option>
        <option>Eletrônicos</option>
      <option>Casa e decoração</option>
      <option>Cuidados pessoais</option>
      <option>Ferramentas</option>
      <option>Produtos domésticos</option>
         <span asp-validation-for="Categoria" class=text-warning></span>
    </select>
  </div>
  <div class="d-flex gap-5 mt-6">
    <button type="submit" class="btn btn-success w-50">Adicionar</button>
    <a class="btn btn-primary w-50" asp-controller="Produtos" asp-action="Index">Voltar</a>
  </div>
</form>
</div>

Views/Produtos/Editar.cshtml
@model ProdutosModel
@{
	ViewData["title"] = "Editar produtos";
}

<div class="container bg-dark p-5 rounded-5">
      <div class="mb-5 text-center">
        <h1 class=text-light>Editar produtos</h1>
    </div>

    <form methos="post" asp-controller="Produtos" asp-action="Editar">
         <input type="hidden" asp-for="ProdutoId"/>
  <div class="form-group">
    <label for="Nome">Nome:</label>
    <input type="text" class="form-control" asp-for="Nome" id="Nome" placeholder="Digite nome do produto">
  </div>
   <div class="form-group">
    <label for="Descricao">Descrição: </label>
    <input type="text" class="form-control" asp-for="Descricao" id="Descricao" placeholder="Digite uma breve descrição do produto">
  </div>
   <div class="form-group">
    <label for="Quantidade">Quantidade: </label>
    <input type="number" class="form-control" asp-for="Quantidade" id="Quantidade" placeholder="Digite a quantidade">
  </div>
  <div class="form-group">
    <label for="Categoria">Categoria:</label>
    <select class="form-control mb-5"  asp-for="Categoria" id="Categoria" placeholder="Selecione a categoria">
        <option> Selecione a categoria</option>
        <option>Eletrônicos</option>
      <option>Casa e decoração</option>
      <option>Cuidados pessoais</option>
      <option>Ferramentas</option>
      <option>Produtos domésticos</option>
    </select>
  </div>
  <div class="d-flex gap-5 mt-6">
    <button type="submit" class="btn btn-success w-50">Salvar alteração</button>
    <a class="btn btn-primary w-50" asp-controller="Produtos" asp-action="Index">Voltar</a>
  </div>
</form>
</div>

Views/Produtos/Excluir.cshtml
@model ProdutosModel
@{
    ViewData["title"] = "Excluir produtos";
}

<div class="container bg-dark p-5 rounded-5">
      <div class="mb-5 text-center">
        <h1 class=text-light>Editar produtos</h1>
    </div>

    <form methos="post" asp-controller="Produtos" asp-action="Excluir">
         <input type="hidden" asp-for="ProdutoId"/>
  <div class="form-group">
    <label for="Nome">Nome:</label>
    <input type="text" class="form-control" asp-for="Nome" id="Nome" placeholder="Digite nome do produto">
  </div>
   <div class="form-group">
    <label for="Descricao">Descrição: </label>
    <input type="text" class="form-control" asp-for="Descricao" id="Descricao" placeholder="Digite uma breve descrição do produto">
  </div>
   <div class="form-group">
    <label for="Quantidade">Quantidade: </label>
    <input type="number" class="form-control" asp-for="Quantidade" id="Quantidade" placeholder="Digite a quantidade">
  </div>
  <div class="form-group">
    <label for="Categoria">Categoria:</label>
    <select class="form-control mb-5"  asp-for="Categoria" id="Categoria" placeholder="Selecione a categoria">
        <option> Selecione a categoria</option>
        <option>Eletrônicos</option>
      <option>Casa e decoração</option>
      <option>Cuidados pessoais</option>
      <option>Ferramentas</option>
      <option>Produtos domésticos</option>
    </select>
  </div>
  <div class="d-flex gap-5 mt-6">
    <button type="submit" class="btn btn-danger w-50">Excluir produto</button>
    <a class="btn btn-primary w-50" asp-controller="Produtos" asp-action="Index">Voltar</a>
  </div>
</form>
</div>

Views/Produtos/Index.cshtml
@model IEnumerable<ProdutosModel>

@{
	ViewData["title"] = "Página principal";
}
<div class="container">
     <div class="d-flex justify-content-between align-items-center mb-5">
     <h1>Produtos</h1>
     <a class="btn btn-success mx-2" asp-controller="Produtos" asp-action="Cadastrar">Cadastrar novo produto</a>
     </div>  
    @if (TempData["MensagemSucesso"] != null)
    {
            <div class="alert alert-success bg-success text-light" role="alert">
            @TempData["MensagemSucesso"]
            </div>
    }
<table id="Produtos" class="table table-hover table-dark">
     <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Categoria</th>
      <th scope="col">Data de Cadastro</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
        @if (Model != null)
        {
            @foreach(var produto in Model)
            {
                <tr>
                <th scope="row">@produto.Nome</th>
                <td>@produto.Descricao</td>
                <td>@produto.Quantidade</td>
                <td>@produto.Categoria</td> 
                <td>@produto.DataCadastro</td> 
                <td>
                   <a class="btn btn-primary mx-2" asp-controller="Produtos" asp-action="Editar" asp-route-id="@produto.ProdutoId">Editar</a>
                   <a class="btn btn-danger mx-2" asp-controller="Produtos" asp-action="Excluir" asp-route-id="@produto.ProdutoId">Excluir</a>
               </td>
                </tr>
            }
        }
  </tbody>
</table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gerenciamento de Loja</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GerenciamentoLojaMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
   <link href="https://cdn.datatables.net/v/dt/dt-2.0.1/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Gerenciamento de Loja</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link  text-light" asp-area="" asp-controller="Home" asp-action="Index">Home <i class="bi bi-house mx-2"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos <i class="bi bi-bag mx-2"></i></a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionários <i class="bi bi-people mx-2"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2024 - Gerenciamento de Loja - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.0.1/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>